services:
  - type: web
    name: auto-mod-pro-v2
    runtime: python3
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: DISCORD_CLIENT_SECRET
        sync: false
      - key: DISCORD_REDIRECT_URI
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: PYTHONUNBUFFERED
        value: "1"
    healthCheckPath: /health
